repository: intotheodd
staticman:
  branch: gh-pages
permalink: /:slug-:month:day:short_year
baseurl: /intotheodd
include: ['_pages']
title: Jekyll-db
description:
google_analytics:
show_downloads: true
